version: '3'
services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
  duckdb:
    image: duckdb/duckdb
    volumes:
      - ./data:/data
    ports:
      - "5000:5000"
